### PR TITLE
generate dependency graph for modules and crates in ArceOs

### PR DESCRIPTION
**Pull request by Tim-C1**

### CODE REVIEW

**Comment by chyyuu** [comment]
Good work! Please fix the clippy waring in  CI.  @Tim-C1

**Comment by chyyuu** [comment]
Good work! Please fix the clippy warning in CI

**Comment by Tim-C1** [comment]
> Good work! Please fix the clippy waring in CI. @Tim-C1

I think now the clippy should pass, I make the tool folder independent of arceos workspace

**Review by chyyuu — APPROVED** [review]

**Comment by chyyuu** [comment]
https://github.com/orgs/rcore-os/discussions/19#discussioncomment-5867882 可以看到展示效果。这个打下了一个很好的基础，还可以进一步扩展和改进！

**Pull request merged**
